version: '3.8'

services:
  jekyll_site:
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - ./jekyll:/srv/jekyll
      - ./content/assets:/srv/jekyll/content/assets
    command: jekyll serve --host 0.0.0.0 --trace
