SELECT A.ANS_ID AS ANS_IDA,A.LINKED_QUES_ID AS LINKED_QUES_IDA,A.LINKED_CAT_ID AS LINKED_CAT_IDA,A.ANSWER AS ANSWERA,A.CREATION_DATE AS CREATION_DATE_ANS_WALA,A.LAST_UPDATION_DATE AS LAST_UPDATION_DATE_ANS_WALA,A.RATING AS RATING_ANS_WALA,A.LAST_READ_DATE AS LAST_READ_DATE_ANS_WALA,Q.QUES_ID AS QUES_IDQ,Q.LINKED_CAT_ID AS LINKED_CAT_IDQ,Q.QUES AS QUESQ,Q.CREATION_DATE AS CREATION_DATE_QUES_WALA,Q.LAST_UPDATION_DATE AS LAST_UPDATION_DATE_QUES_WALA,Q.RATING AS RATING_QUES_WALA,Q.LAST_READ_DATE AS LAST_READ_DATE_QUES_WALA,Q.HIDDEN AS HIDDENQ FROM T_CATG_QUES Q,T_CATG_QUES_ANS A WHERE Q.QUES_ID = A.LINKED_QUES_ID AND Q.LINKED_CAT_ID = A.LINKED_CAT_ID AND Q.QUES_ID = '1' AND Q.LINKED_CAT_ID = '45'


--=====================================

DELIMITER //

CREATE PROCEDURE GetCategoryQuestionWithAnswer()
BEGIN
	SELECT A.ANS_ID AS ANS_IDA,A.LINKED_QUES_ID AS LINKED_QUES_IDA,A.LINKED_CAT_ID AS LINKED_CAT_IDA,A.ANSWER AS ANSWERA,A.CREATION_DATE AS CREATION_DATE_ANS_WALA,A.LAST_UPDATION_DATE AS LAST_UPDATION_DATE_ANS_WALA,A.RATING AS RATING_ANS_WALA,A.LAST_READ_DATE AS LAST_READ_DATE_ANS_WALA,Q.QUES_ID AS QUES_IDQ,Q.LINKED_CAT_ID AS LINKED_CAT_IDQ,Q.QUES AS QUESQ,Q.CREATION_DATE AS CREATION_DATE_QUES_WALA,Q.LAST_UPDATION_DATE AS LAST_UPDATION_DATE_QUES_WALA,Q.RATING AS RATING_QUES_WALA,Q.LAST_READ_DATE AS LAST_READ_DATE_QUES_WALA,Q.HIDDEN AS HIDDENQ FROM T_CATG_QUES Q,T_CATG_QUES_ANS A WHERE Q.QUES_ID = A.LINKED_QUES_ID AND Q.LINKED_CAT_ID = A.LINKED_CAT_ID AND Q.QUES_ID = '1' AND Q.LINKED_CAT_ID = '45';
END //

DELIMITER ;

--==============================================

DROP
PROCEDURE `GetCategoryQuestionWithAnswer`;
CREATE DEFINER = `root`@`localhost` PROCEDURE `GetCategoryQuestionWithAnswer`(
    IN `INP_QUES_ID` INT,
    IN `INP_CAT_ID` INT
) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER
BEGIN
    SELECT
        A.ANS_ID AS ANS_IDA,
        A.LINKED_QUES_ID AS LINKED_QUES_IDA,
        A.LINKED_CAT_ID AS LINKED_CAT_IDA,
        A.ANSWER AS ANSWERA,
        A.CREATION_DATE AS CREATION_DATE_ANS_WALA,
        A.LAST_UPDATION_DATE AS LAST_UPDATION_DATE_ANS_WALA,
        A.RATING AS RATING_ANS_WALA,
        A.LAST_READ_DATE AS LAST_READ_DATE_ANS_WALA,
        Q.QUES_ID AS QUES_IDQ,
        Q.LINKED_CAT_ID AS LINKED_CAT_IDQ,
        Q.QUES AS QUESQ,
        Q.CREATION_DATE AS CREATION_DATE_QUES_WALA,
        Q.LAST_UPDATION_DATE AS LAST_UPDATION_DATE_QUES_WALA,
        Q.RATING AS RATING_QUES_WALA,
        Q.LAST_READ_DATE AS LAST_READ_DATE_QUES_WALA,
        Q.HIDDEN AS HIDDENQ
    FROM
        T_CATG_QUES Q,
        T_CATG_QUES_ANS A
    WHERE
        Q.QUES_ID = A.LINKED_QUES_ID AND Q.LINKED_CAT_ID = A.LINKED_CAT_ID AND Q.QUES_ID = INP_QUES_ID AND Q.LINKED_CAT_ID = INP_CAT_ID;
END


--==============================================================

SET @p0='1'; SET @p1='45'; CALL `GetCategoryQuestionWithAnswer`(@p0, @p1);

--===============================================================

