spring:
  application:
   name: demo
  mongodb:
    uri: mongodb://localhost:27017/redis_kafka_demo
    database: redis_kafka_demo
  redis:
    data:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: redis-kafka-demo-group
      auto-offset-reset: earliest

server:
  port: 8089

app:
  kafka:
    todo-topic: todo-events
